# Generated by Django 3.2.18 on 2023-05-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_account_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='account',
            name='review',
            field=models.CharField(blank=True, default='Review', max_length=100, null=True),
        ),
    ]
